--------------------------------------------------------
--  TABLES
--------------------------------------------------------

  CREATE TABLE "BSM_SYSVAR" 
  (	"CODE" VARCHAR2(50 BYTE)
  , "WAARDE" VARCHAR2(100 BYTE)
  , "OMSCHRIJVING" VARCHAR2(250 BYTE)
  , "TOON_VOLGNR" NUMBER(3,0)
  , CONSTRAINT "SVR_KEY" PRIMARY KEY ("CODE") USING INDEX ENABLE
  );

  COMMENT ON TABLE "BSM_SYSVAR"  IS 'Systeem variabelen';

  CREATE TABLE "BSM_DISC_GROEPEN" 
  ("VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "NAAM" VARCHAR2(50 BYTE), "OMSCHRIJVING" VARCHAR2(500 BYTE)
  ,  CONSTRAINT "DGP_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );
 
  COMMENT ON TABLE "BSM_DISC_GROEPEN"  IS 'Discussiegroepen';

  CREATE TABLE "BSM_DOC_HIERARCHIEEN" 
  ( "DHE_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "NAAM" VARCHAR2(2000 BYTE) NOT NULL ENABLE
  , "DATUM_OPNAME" DATE NOT NULL ENABLE
  , "INFO" VARCHAR2(4000 BYTE)
  , "DHE_DHE_VOLGNR" NUMBER(10,0)
  , CONSTRAINT "DHE_PK" PRIMARY KEY ("DHE_VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_DOC_INFO" 
  ( "DCT_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "NAAM" VARCHAR2(2000 BYTE) NOT NULL ENABLE
  , "GROOTTE" NUMBER(12,0), "DATUM" DATE NOT NULL ENABLE
  , "DATUM_OPNAME" DATE
  , "DATUM_GERAADPLEEGD" DATE
  , "INFO" VARCHAR2(4000 BYTE)
  , CONSTRAINT "DCT_PK" PRIMARY KEY ("DCT_VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_DOC_LABELS" 
  (	"DLL_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "LABEL" VARCHAR2(50 BYTE) NOT NULL ENABLE
  , "INCL_SUBDIRECTORIES" VARCHAR2(1 BYTE)
  );
  
  CREATE INDEX "BSM_DLL_LABEL_IDX" ON "BSM_DOC_LABELS" ("LABEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS;

  CREATE TABLE "BSM_DOCUMENTEN" 
  ( "NAME" VARCHAR2(256 BYTE) NOT NULL ENABLE
  , "MIME_TYPE" VARCHAR2(128 BYTE), "DOC_SIZE" NUMBER
  , "DAD_CHARSET" VARCHAR2(128 BYTE)
  , "LAST_UPDATED" DATE
  , "CONTENT_TYPE" VARCHAR2(128 BYTE)
  , "CONTENT" LONG RAW
  , "BLOB_CONTENT" BLOB
  , "DCE_VOLGNR" NUMBER(10,0)
  , "BLOB_CONTENT_THUMBNAIL" BLOB
  , CONSTRAINT "DCN_KEY" PRIMARY KEY ("NAME") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_GROEPEN" 
  (	"GRP_VOLGNR" NUMBER(10,0)
  , "OMSCHRIJVING" VARCHAR2(100 BYTE)
  );

  CREATE TABLE "BSM_DOCUMENT_TYPE" 
  ( "DCE_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(500 BYTE)
  , "FOTOALBUM" VARCHAR2(1 BYTE)
  , CONSTRAINT "DCE_PK" PRIMARY KEY ("DCE_VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_ERRORLOG" 
  ( "DATUM" DATE
  , "ONDERDEEL" VARCHAR2(500 BYTE)
  , "SQL_CODE" VARCHAR2(500 BYTE)
  , "SQL_ERRMSG" VARCHAR2(2000 BYTE)
  , "GEBRUIKER" VARCHAR2(200 BYTE)
  , "ADDITIONEEL" VARCHAR2(2000 BYTE)
  );

  CREATE TABLE "BSM_EVENTS" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "TITEL" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(2000 BYTE)
  , "BEGINDATUM" DATE
  , "EINDDATUM" DATE
  , "LOCATIE" VARCHAR2(200 BYTE)
  , CONSTRAINT "EVT_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_FILE_TYPEN" 
  ( "FTE_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(50 BYTE) NOT NULL ENABLE
  , "ICON_BESTAND" VARCHAR2(50 BYTE) NOT NULL ENABLE
  , "EXTENTIE" VARCHAR2(10 BYTE) NOT NULL ENABLE
  , CONSTRAINT "FTE_1_PK" PRIMARY KEY ("FTE_VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_GEBRUIKERS" 
  ( "GBR_VOLGNR" NUMBER(10,0)
  , "LOGINNAAM" VARCHAR2(50 BYTE)
  , "VOORNAAM" VARCHAR2(25 BYTE)
  , "VOORVOEGSEL" VARCHAR2(15 BYTE)
  , "ACHTERNAAM" VARCHAR2(50 BYTE)
  , "ADRES" VARCHAR2(100 BYTE)
  , "POSTCODE" VARCHAR2(6 BYTE)
  , "WOONPLAATS" VARCHAR2(100 BYTE)
  , "TELEFOON_PRIVE" VARCHAR2(11 BYTE)
  , "MOBIEL_NUMMER" VARCHAR2(11 BYTE)
  , "GEBOORTEDATUM" DATE
  , "DATUM_INDIENST" DATE
  , "DATUM_UITDIENST" DATE
  , "GRP_VOLGNUMMER" NUMBER(3,0)
  , CONSTRAINT "GBS_PK" PRIMARY KEY ("GBR_VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_IDEEEN" 
  ( "VOLGNR" NUMBER(11,0)
  , "OPMERKING" VARCHAR2(255 BYTE)
  , "NAAM" VARCHAR2(255 BYTE)
  , "EMAIL" VARCHAR2(255 BYTE)
  , "HOMEPAGENAAM" VARCHAR2(255 BYTE)
  , "HOMEPAGE" VARCHAR2(255 BYTE)
  , "DATUM" DATE
  , "TYPE_IDEEEN" NUMBER(11,0)
  , "GBR_VOLGNR" NUMBER(11,0)
  , CONSTRAINT "IDN_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_KALENDER" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "DATUM" DATE
  , "TITEL" VARCHAR2(100 BYTE)
  , "OMSCHRIJVING" VARCHAR2(2000 BYTE)
  , CONSTRAINT "KLR_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );
 
  COMMENT ON TABLE "BSM_KALENDER"  IS 'Kalender';

  CREATE TABLE "INFO_PAGINAS" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "INHOUD" CLOB
  ,  CONSTRAINT "IPS_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  COMMENT ON TABLE "INFO_PAGINAS"  IS 'Informatie Paginas';

  CREATE TABLE "MAILBERICHT" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "ONDERWERP" VARCHAR2(500 BYTE)
  , "BERICHTTEKST" VARCHAR2(4000 BYTE)
  , "ADRES" VARCHAR2(1000 BYTE)
  , "DATUM_BERICHT" DATE
  , "GBRVOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "DATUM_VERWERKT" DATE
  , "STATUS" VARCHAR2(1 BYTE)
  );

  CREATE TABLE "MAILGEBRUIKERS" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "LOGINID" VARCHAR2(100 BYTE)
  , "WACHTWOORD" VARCHAR2(100 BYTE)
  , "VOORNAAM" VARCHAR2(100 BYTE)
  , "TUSSENVOEGSEL" VARCHAR2(100 BYTE)
  , "ACHTERNAAM" VARCHAR2(100 BYTE)
  , "TEMVOLGNR" NUMBER(10,0)
  , "SESSION_ID" VARCHAR2(100 BYTE)
  );

  CREATE TABLE "BSM_LOGIN" 
  (	"GBR_VOLGNR" NUMBER
  , "DATUM" DATE
  );
  
  COMMENT ON TABLE "BSM_LOGIN"  IS 'Login informatie';

  CREATE TABLE "MAILTEAMS" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(100 BYTE)
  );

  CREATE TABLE "SOORT_DEELNEMERS" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(50 BYTE) DEFAULT NULL
  ,  CONSTRAINT "SDS_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  COMMENT ON TABLE "SOORT_DEELNEMERS"  IS 'Soort deelnemers (spelers)';

  CREATE TABLE "TEAMS" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "NAAM" VARCHAR2(50 BYTE) DEFAULT NULL
  , "KLASSE" VARCHAR2(100 BYTE) DEFAULT NULL
  , "SOORT" VARCHAR2(10 BYTE) DEFAULT NULL
  , "HOMEPAGE" VARCHAR2(100 BYTE) DEFAULT NULL
  , "FOTO" VARCHAR2(100 BYTE) DEFAULT NULL
  , "GEBRUIKERSID" VARCHAR2(50 BYTE) DEFAULT NULL
  , "DISPLAY_VOLGNR" NUMBER(11,0)
  , "VRIJETEKST" CLOB
  , "SPONSORNAAM" VARCHAR2(200 BYTE)
  , "SPONSORFOTO" VARCHAR2(100 BYTE)
  , "SPONSORURL" VARCHAR2(100 BYTE)
  , "STANDURL" VARCHAR2(100 BYTE)
  , "HOOFDTEAM" VARCHAR2(1 BYTE)
  , CONSTRAINT "TEM_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE 
  ); 

  COMMENT ON TABLE "TEAMS"  IS 'Teams';

  CREATE TABLE "TYPE_GASTENBOEK" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(50 BYTE) DEFAULT NULL
  , CONSTRAINT "TGK_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  ); 

  COMMENT ON TABLE "TYPE_GASTENBOEK"  IS 'Type Gastenboek';

  CREATE TABLE "BSM_FUNCTIES" 
  (	"FUN_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "NAAM_FUNCTIE" VARCHAR2(50 BYTE)
  , "OMSCHRIJVING_FUNCTIE" VARCHAR2(2000 BYTE)
  , "NIVO_MENU" NUMBER(1,0) NOT NULL ENABLE
  , "URL" VARCHAR2(100 BYTE)
  , "FUN_VOLGNR_FK" NUMBER(10,0)
  , "TOON_VOLGNR" NUMBER(10,0)
  , "PLAATJE" VARCHAR2(50 BYTE)
  , "TYPE_INFO_VOLGNR" NUMBER(11,0)
  , "NAAM_FUNCTIE_EN" VARCHAR2(50 BYTE)
  , "OMSCHRIJVING_FUNCTIE_EN" VARCHAR2(2000 BYTE)
  , "DOCUMENT_VOLGNR" NUMBER(11,0)
  , "TYPE" VARCHAR2(50 BYTE)
  , "TARGET" VARCHAR2(100 BYTE)
  , "FOTOALBUM_VOLGNR" NUMBER(11,0)
  , CONSTRAINT "FUNPK" PRIMARY KEY ("FUN_VOLGNR") USING INDEX ENABLE
  );
 
  COMMENT ON TABLE "BSM_FUNCTIES"  IS 'Functies menuingangen website';

  CREATE TABLE "BSM_GBR_GRP" 
  (	"GBR_VOLGNUMMER" NUMBER(10,0)
  , "GRP_VOLGNUMMER" NUMBER(10,0)
  );

  CREATE TABLE "TYPE_INFO" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(50 BYTE) DEFAULT NULL
  , "OMSCHRIJVING_EN" VARCHAR2(50 BYTE) DEFAULT NULL
  , "ARCHIEF" VARCHAR2(1 BYTE)
  , "LAATSTE_UPDATE" DATE
  , CONSTRAINT "TIO_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );
 
  COMMENT ON TABLE "TYPE_INFO"  IS 'Type Informatie paginas';

  CREATE TABLE "BSM_DISC_NEW" 
  ( "GBR_VOLGNR" NUMBER(11,0)
  , "DISC_SOORT" VARCHAR2(3 BYTE)
  , "DISC_VOLGNR" NUMBER(11,0)
  , "DATUM" DATE
  );
  
  CREATE TABLE "BSM_LINK_EIGENAAR" 
  ( "VOLGNR" NUMBER(3,0) NOT NULL ENABLE
  , "GEBRUIKERSID" VARCHAR2(20 BYTE) NOT NULL ENABLE
  , "WACHTWOORD" VARCHAR2(20 BYTE) NOT NULL ENABLE
  , "VOORNAAM" VARCHAR2(50 BYTE)
  , "TUSSENVOEGSEL" VARCHAR2(20 BYTE)
  , "ACHTERNAAM" VARCHAR2(50 BYTE)
  );

  CREATE TABLE "BSM_LINKGROEP" 
  ( "VOLGNR" NUMBER(3,0) NOT NULL ENABLE
  , "GROEPNAAM" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(500 BYTE)
  , "DISPLAY_VOLGNR" NUMBER(3,0)
  , "EIGENAAR_VOLGNR" NUMBER(3,0) NOT NULL ENABLE
  );

  CREATE TABLE "BSM_LINKS" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "TITEL" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "URL" VARCHAR2(500 BYTE) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(500 BYTE)
  , "GROEP_VOLGNR" NUMBER(3,0)
  , "EIGENAAR_VOLGNR" NUMBER(3,0)
  );

  CREATE TABLE "BSM_MUTATIES" 
  ( "SOORT" VARCHAR2(10 BYTE)
  , "KEY_SOORT" NUMBER(11,0)
  , "DATUM" DATE
  , "GBR_VOLGNR" NUMBER(11,0)
  , "MUTATIE_TYPE" VARCHAR2(10 BYTE)
  ); 

  COMMENT ON TABLE "BSM_MUTATIES"  IS 'Gebruikt voor bijhouden mutaties op wedstrijden';

  CREATE TABLE "BSM_SECURITY" 
  ( "DATUM" DATE
  , "CAMERA" VARCHAR2(1 BYTE)
  );

  CREATE TABLE "BSM_SMOELEN" 
  (	"SML_VOLGNR" NUMBER(10,0)
  , "PLAATJE" VARCHAR2(100 BYTE)
  , "GBR_VOLGNUMMER" NUMBER(10,0)
  );

  CREATE TABLE "BSM_SPEELLOKATIES" 
  ( "VOLGNR" NUMBER(12,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(200 BYTE) NOT NULL ENABLE
  ,  CONSTRAINT "SLE_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );
 
  COMMENT ON TABLE "BSM_SPEELLOKATIES"  IS 'Lokaties waarop gespeeld kan worden';

  CREATE TABLE "BSM_SPONSOR_LOGOS" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "TITEL" VARCHAR2(50 BYTE)
  , "URL" VARCHAR2(100 BYTE)
  , "BESTANDSNAAM" VARCHAR2(100 BYTE)
  , "DISPLAY_VOLGNR" NUMBER(10,0)
  , "TONEN_IN_CARROUSSEL" VARCHAR2(3 BYTE)
  , CONSTRAINT "SLS_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_SYSTEEM_MEDEDELING" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "DATUM" DATE NOT NULL ENABLE
  , "MEDEDELING" VARCHAR2(4000 BYTE)
  , "TYPE" VARCHAR2(50 BYTE)
  , "ACTIEF" VARCHAR2(1 BYTE)
  , "OMSCHRIJVING" VARCHAR2(100 BYTE)
  ); 

  COMMENT ON TABLE "BSM_SYSTEEM_MEDEDELING"  IS 'Systeem mededelingen Oracle beheer';

  CREATE TABLE "BSM_TEM_GBR" 
  ( "TEM_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "GBR_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , CONSTRAINT "TEMGBR_PK" PRIMARY KEY ("TEM_VOLGNR", "GBR_VOLGNR") USING INDEX ENABLE
  ); 

  COMMENT ON TABLE "BSM_TEM_GBR"  IS 'Teambeheerders';

  CREATE TABLE "BSM_TRAININGSTIJD" 
  ( "TEM_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "ZO_TIJD" VARCHAR2(10 BYTE)
  , "MA_TIJD" VARCHAR2(10 BYTE)
  , "DI_TIJD" VARCHAR2(10 BYTE)
  , "WO_TIJD" VARCHAR2(10 BYTE)
  , "DO_TIJD" VARCHAR2(10 BYTE)
  , "VR_TIJD" VARCHAR2(10 BYTE)
  , "ZA_TIJD" VARCHAR2(10 BYTE)
  , "ZO_LOK" VARCHAR2(200 BYTE)
  , "MA_LOK" VARCHAR2(200 BYTE)
  , "DI_LOK" VARCHAR2(200 BYTE)
  , "WO_LOK" VARCHAR2(200 BYTE)
  , "DO_LOK" VARCHAR2(200 BYTE)
  , "VR_LOK" VARCHAR2(200 BYTE)
  , "ZA_LOK" VARCHAR2(200 BYTE)
  , CONSTRAINT "BSM_TRAININGSTIJD_PK" PRIMARY KEY ("TEM_VOLGNR") USING INDEX ENABLE
  );
 
  COMMENT ON TABLE "BSM_TRAININGSTIJD"  IS 'Trainingen';

  CREATE TABLE "BSM_TYPE_LEDEN" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , CONSTRAINT "TLD_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );  

  COMMENT ON TABLE "BSM_TYPE_LEDEN"  IS 'Type Leden';

  CREATE TABLE "BSM_TYPE_TEAMS" 
  ( "CODE" VARCHAR2(10 BYTE) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "DISPLAY_VOLGNR" NUMBER(3,0)
  , "OMSCHRIJVING_EN" VARCHAR2(100 BYTE)
  , CONSTRAINT "TTS_PK" PRIMARY KEY ("CODE") USING INDEX ENABLE
  );
 
  COMMENT ON TABLE "BSM_TYPE_TEAMS"  IS 'Type Teams';

  CREATE TABLE "DOCUMENTEN" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "INHOUD" CLOB
  , "TITEL" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "DATUM_TOEGEVOEGD" DATE
  , "ARCHIEF" VARCHAR2(1 BYTE)
  , "TAAL" VARCHAR2(2 BYTE) NOT NULL ENABLE
  , "SITE_STYLE" VARCHAR2(1 BYTE)
  );

  CREATE TABLE "BSM_ROL_GBR" 
  (	"GBR_VOLGNR" NUMBER(10,0)
  , "ROL_VOLGNR" NUMBER(10,0)
  , "VOLGNR" NUMBER(10,0)
  , CONSTRAINT "RGR_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );
  
  CREATE TABLE "BSM_EMAILADRES" 
  (	"VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "EMAILADRES" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(100 BYTE)
  , CONSTRAINT "EMS_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  CREATE TABLE "BSM_EMAILFORWARDS" 
  (	"VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "EML_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "EMAILADRES" VARCHAR2(100 BYTE)
  , "NAAM" VARCHAR2(100 BYTE)
  , CONSTRAINT "EMD_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "EMD_EMS_FK" FOREIGN KEY ("EML_VOLGNR") REFERENCES "BSM_EMAILADRES" ("VOLGNR") ENABLE
  );

  CREATE TABLE "GEBRUIKERS" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "GEBRUIKERSID" VARCHAR2(50 BYTE) NOT NULL ENABLE
  , "ACHTERNAAM" VARCHAR2(50 BYTE)
  , "TUSSENVOEGSEL" VARCHAR2(50 BYTE)
  , "VOORNAAM" VARCHAR2(50 BYTE)
  , "WACHTWOORD" VARCHAR2(50 BYTE)
  , "SESSION_ID" VARCHAR2(50 BYTE)
  , "DATUM_INLOG" DATE
  , "DATUM_UITLOG" DATE
  , "TYPE_GEBRUIKER" VARCHAR2(10 BYTE)
  , "INITIALEN" VARCHAR2(10 BYTE)
  , "EMAIL" VARCHAR2(100 BYTE)
  , "TELEFOONNUMMER" VARCHAR2(20 BYTE)
  , "STATUS" VARCHAR2(50 BYTE)
  , "LIDNUMMER" VARCHAR2(10 BYTE)
  , "GEBOORTEDATUM" DATE
  , "REGISTREERSID" VARCHAR2(50 BYTE)
  , "PAPIEREN_NIEUWS" VARCHAR2(1 BYTE)
  , "PELLIKAAN_AL_LID" VARCHAR2(1 BYTE)
  , "PELLIKAAN_MEEDOEN" VARCHAR2(1 BYTE)
  , CONSTRAINT "GBR_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  COMMENT ON TABLE "GEBRUIKERS"  IS 'Gebruikers beheer';

  CREATE TABLE "BSM_AANMELDINGEN" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "EVT_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "ACHTERNAAM" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "TUSSENVOEGSEL" VARCHAR2(20 BYTE)
  , "VOORNAAM" VARCHAR2(50 BYTE)
  , "STRAATNAAM" VARCHAR2(100 BYTE)
  , "HUISNUMMER" VARCHAR2(20 BYTE)
  , "POSTCODE" VARCHAR2(20 BYTE)
  , "PLAATS" VARCHAR2(100 BYTE)
  , "TELEFOON" VARCHAR2(12 BYTE)
  , "MOBIEL" VARCHAR2(12 BYTE)
  , "EMAIL" VARCHAR2(100 BYTE)
  , "GEBOORTEDATUM" DATE
  , "EXTRA1" VARCHAR2(2000 BYTE)
  , "EXTRA2" VARCHAR2(2000 BYTE)
  , "EXTRA3" VARCHAR2(2000 BYTE)
  , "EXTRA4" VARCHAR2(2000 BYTE)
  , "EXTRA5" VARCHAR2(2000 BYTE)
  , "EXTRA6" VARCHAR2(2000 BYTE)
  , "AANTAL_INTRODUCEES" NUMBER(2,0)
  , "AANTAL_INTROD_REUNIE" NUMBER(2,0)
  , CONSTRAINT "AMG_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "AMG_EVT_FK" FOREIGN KEY ("EVT_VOLGNR") REFERENCES "BSM_EVENTS" ("VOLGNR") ENABLE
  );

  CREATE TABLE "BSM_TYPEAKTIES"
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(500 BYTE) NOT NULL ENABLE
  , CONSTRAINT "TAE_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );
  
  CREATE TABLE "BSM_AKTIEPUNTEN" 
  ("VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "AKTIEPUNT" VARCHAR2(500 BYTE) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(1000 BYTE)
  , "STATUS" VARCHAR2(1 BYTE)
  , "AANMAAKDATUM" DATE
  , "WIJZIGDATUM" DATE
  , "TYPE_AKTIE" NUMBER(11,0)
  ,  CONSTRAINT "ATE_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  ,  CONSTRAINT "ATE_TAE_FK" FOREIGN KEY ("TYPE_AKTIE") REFERENCES "BSM_TYPEAKTIES" ("VOLGNR") ENABLE
  );

  COMMENT ON TABLE "BSM_AKTIEPUNTEN"  IS 'Aktiepunten';

  CREATE TABLE "BSM_AKTIE_LOGS" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "DATUM" DATE NOT NULL ENABLE
  , "AKE_VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(4000 BYTE)
  ,  CONSTRAINT "ALG_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  ,  CONSTRAINT "ALG_AKE_FK" FOREIGN KEY ("AKE_VOLGNR") REFERENCES "BSM_AKTIEPUNTEN" ("VOLGNR") ENABLE
  );

  COMMENT ON TABLE "BSM_AKTIE_LOGS"  IS 'Aktiepunten Logs';
  
  CREATE TABLE "BSM_BEHEER_MODULES" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "MODULENAAM" VARCHAR2(100 BYTE)
  , "MODULEID" VARCHAR2(100 BYTE)
  , "NIVO" NUMBER(3,0)
  , "FOLDERNAAM" VARCHAR2(100 BYTE)
  , "BMS_VOLGNR" NUMBER(3,0)
  , "DISPLAY_VOLGNR" NUMBER(3,0)
  , CONSTRAINT "BMS_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  );

  COMMENT ON TABLE "BSM_BEHEER_MODULES"  IS 'BeheerModules java';

  CREATE TABLE "BSM_ROLLEN" 
  (	"ROL_VOLGNR" NUMBER(10,0)
  , "ROLNAAM" VARCHAR2(50 BYTE)
  , CONSTRAINT "ROL_PK" PRIMARY KEY ("ROL_VOLGNR") USING INDEX ENABLE
  );

  COMMENT ON TABLE "BSM_ROLLEN"  IS 'Rollen beheer Oracle';
   
  CREATE TABLE "BSM_BMS_ROL" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "ROL_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "BMS_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  ,  CONSTRAINT "BRL_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  ,  CONSTRAINT "BRL_BMS_FK" FOREIGN KEY ("BMS_VOLGNR") REFERENCES "BSM_BEHEER_MODULES" ("VOLGNR") ENABLE
  ,  CONSTRAINT "BRL_ROL_FK" FOREIGN KEY ("ROL_VOLGNR") REFERENCES "BSM_ROLLEN" ("ROL_VOLGNR") ENABLE
  ); 

  COMMENT ON TABLE "BSM_BMS_ROL"  IS 'Beheermodules per rol';

  CREATE TABLE "BSM_FUN_ROL" 
  ( "FUN_VOLGNR" NUMBER(10,0)
  , "ROL_VOLGNR" NUMBER(10,0)
  );

  CREATE TABLE "BSM_CIES" 
  (	"VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "ARCHIEF" VARCHAR2(1 BYTE) NOT NULL ENABLE
  );

  COMMENT ON TABLE "BSM_CIES"  IS 'Commissies';
 
  CREATE TABLE "BSM_TYPE_CONDOLEANCE" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(50 BYTE)
  , "FOTO" VARCHAR2(1000 BYTE)
  , "TEKST" VARCHAR2(4000 BYTE)
  , "TEKST_EN" VARCHAR2(4000 BYTE)
  , "FOTO_WIDTH" VARCHAR2(4 BYTE)
  , "FOTO_HEIGHT" VARCHAR2(4 BYTE)
  );

  COMMENT ON TABLE "BSM_TYPE_CONDOLEANCE"  IS 'Type condoleances';

  CREATE TABLE "BSM_CONDOLEANCE" 
  (	"VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "OPMERKING" VARCHAR2(2000 BYTE)
  , "NAAM" VARCHAR2(255 BYTE)
  , "TYPE_CONDOLEANCE" NUMBER(11,0)
  , "DATUM" DATE
  );

  COMMENT ON TABLE "BSM_CONDOLEANCE"  IS 'Condoleance register';
 
  CREATE TABLE "BSM_DISC_TOPICS" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "ONDERWERP" VARCHAR2(100 BYTE)
  , "OMSCHRIJVING" VARCHAR2(2000 BYTE)
  , "DATUM" DATE
  , "DGP_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "GBR_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , CONSTRAINT "DTC_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "DTC_DGP_FK" FOREIGN KEY ("DGP_VOLGNR") REFERENCES "BSM_DISC_GROEPEN" ("VOLGNR") ENABLE
  , CONSTRAINT "DTC_GBR_FK" FOREIGN KEY ("GBR_VOLGNR") REFERENCES "GEBRUIKERS" ("VOLGNR") ENABLE
  );

  CREATE TABLE "BSM_DISC_REACTIES" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "ONDERWERP" VARCHAR2(100 BYTE)
  , "OMSCHRIJVING" VARCHAR2(2000 BYTE)
  , "DATUM" DATE
  , "DTC_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "GBR_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  ,  CONSTRAINT "DRE_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  ,  CONSTRAINT "DRE_DTC_FK" FOREIGN KEY ("DTC_VOLGNR") REFERENCES "BSM_DISC_TOPICS" ("VOLGNR") ENABLE
  ,  CONSTRAINT "DRE_GBR_FK" FOREIGN KEY ("GBR_VOLGNR") REFERENCES "GEBRUIKERS" ("VOLGNR") ENABLE
  );

  CREATE TABLE "BSM_DOC_DCE" 
  ( "DCE_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "DOC_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , CONSTRAINT "DCEDOC_PK" PRIMARY KEY ("DCE_VOLGNR", "DOC_VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "DCEDOC_DCE_FK" FOREIGN KEY ("DCE_VOLGNR") REFERENCES "BSM_DOCUMENT_TYPE" ("DCE_VOLGNR") ENABLE
  , CONSTRAINT "DCEDOC_DOC_FK" FOREIGN KEY ("DOC_VOLGNR") REFERENCES "BSM_DOC_INFO" ("DCT_VOLGNR") ENABLE
  );

  CREATE TABLE "BSM_LEDEN" 
  ( "VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "ACHTERNAAM" VARCHAR2(100 BYTE)
  , "VOORNAAM" VARCHAR2(50 BYTE)
  , "TUSSENVOEGSEL" VARCHAR2(20 BYTE)
  , "LIDNR" VARCHAR2(10 BYTE)
  , "STRAATNAAM" VARCHAR2(100 BYTE)
  , "HUISNUMMER" VARCHAR2(50 BYTE)
  , "POSTCODE" VARCHAR2(7 BYTE)
  , "WOONPLAATS" VARCHAR2(100 BYTE)
  , "TELEFOON" VARCHAR2(13 BYTE)
  , "MOBIEL" VARCHAR2(13 BYTE)
  , "EMAIL" VARCHAR2(100 BYTE)
  , "GEBOORTEDATUM" DATE
  , "BEGINDATUM_LID" DATE
  , "EINDDATUM_LID" DATE
  , "TLD_VOLGNR" NUMBER(10,0)
  , "AANHEF" VARCHAR2(10 BYTE)
  , "VOORLETTERS" VARCHAR2(15 BYTE)
  , "TOEVOEGING_ADRES" VARCHAR2(50 BYTE)
  , "GEBOORTEPLAATS" VARCHAR2(100 BYTE)
  , "NATIONALITEIT" VARCHAR2(50 BYTE)
  , "GESLACHT" VARCHAR2(4 BYTE)
  , "MUTATIE_DATUM" DATE
  , "REDEN_MUTATIE" VARCHAR2(100 BYTE)
  , "SOORT_LID" VARCHAR2(20 BYTE)
  , "SOORT_LID_BOND" VARCHAR2(20 BYTE)
  , "SPELEND_LID" VARCHAR2(1 BYTE)
  , "NIET_SPELEND_LID" VARCHAR2(1 BYTE)
  , "TEAM_99" VARCHAR2(20 BYTE)
  , "TR_CO" VARCHAR2(50 BYTE)
  , "BEGELEIDER" VARCHAR2(50 BYTE)
  , "DONATEUR" VARCHAR2(1 BYTE)
  , "KADERLID" VARCHAR2(1 BYTE)
  , "ADVERTEERDER" VARCHAR2(1 BYTE)
  , "LVV" VARCHAR2(1 BYTE)
  , "JAAR_LVV" VARCHAR2(4 BYTE)
  , "ERE_LID" VARCHAR2(1 BYTE)
  , "JAAR_ERE_LID" VARCHAR2(4 BYTE)
  , "OMROEPERS" VARCHAR2(1 BYTE)
  , "UMPIRE" VARCHAR2(10 BYTE)
  , "WEDSTR_SECR" VARCHAR2(1 BYTE)
  , "TWEEDE_PENNINGM" VARCHAR2(1 BYTE)
  , "LEDENADMIN" VARCHAR2(1 BYTE)
  , "STRIKE" VARCHAR2(1 BYTE)
  , "CONTRIBUTIE" NUMBER(6,2)
  , "KADERKORTING" NUMBER(6,2)
  , "GEZINSKORTING" NUMBER(6,2)
  ,  CONSTRAINT "LDN_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  ,  CONSTRAINT "LDN_TLD_FK" FOREIGN KEY ("TLD_VOLGNR") REFERENCES "BSM_TYPE_LEDEN" ("VOLGNR") ENABLE
  );

  CREATE TABLE "BSM_LID_CIE" 
  (	"VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "LID_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "CIE_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  );

  CREATE TABLE "BSM_MENU" 
  ( "MNU_VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "OMSCHRIJVING" VARCHAR2(200 BYTE) NOT NULL ENABLE
  , "URL" VARCHAR2(500 BYTE)
  , "HINT" VARCHAR2(500 BYTE)
  , "PLAATJE" VARCHAR2(500 BYTE)
  , "NIVO" NUMBER(2,0)
  , "PARENT" NUMBER(10,0)
  , "WIDTH" NUMBER(10,0)
  , "TARGET" VARCHAR2(100 BYTE)
  , "OMSCHRIJVINGLANG" VARCHAR2(500 BYTE)
  , "TOON_VOLGNR" NUMBER(10,0)
  , "HELPTEKST" CLOB
  ,  CONSTRAINT "MNU_PK" PRIMARY KEY ("MNU_VOLGNR") USING INDEX ENABLE
  ,  CONSTRAINT "MNU_MNU_FK" FOREIGN KEY ("PARENT") REFERENCES "BSM_MENU" ("MNU_VOLGNR") ENABLE
  );
 
  COMMENT ON TABLE "BSM_MENU"  IS 'Gebruikt voor beheermenu Oracle';

  CREATE TABLE "BSM_SUBSCRIPTIONS" 
  ( "SSN_KEY" NUMBER(11,0) NOT NULL ENABLE
  , "ANOUNCEMENT" CLOB NOT NULL ENABLE
  , "GBR_KEY" NUMBER(11,0) NOT NULL ENABLE
  , "LASTNAME_SUBSCRIBER" VARCHAR2(200 BYTE)
  , "FIRSTNAME_SUBSCRIBER" VARCHAR2(200 BYTE)
  , "MIDDELNAME_SUBSCRIBER" VARCHAR2(200 BYTE)
  , "EMAIL_SUBSCRIBER" VARCHAR2(200 BYTE)
  , "PHONE_SUBSCRIBER" VARCHAR2(200 BYTE)
  , "TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE
  , "STARTDATE" DATE
  , "ENDDATE" DATE
  , "DATE_CREATED" DATE NOT NULL ENABLE
  , "ARCHIVE" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE
  , "LANGUAGE" VARCHAR2(2 BYTE) DEFAULT 'NL'
  ,  CONSTRAINT "SSN_KEY" PRIMARY KEY ("SSN_KEY") USING INDEX ENABLE
  ,  CONSTRAINT "SSN_GBR_KEY" FOREIGN KEY ("GBR_KEY") REFERENCES "GEBRUIKERS" ("VOLGNR") ENABLE
  );
 
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."SSN_KEY" IS 'Technical Id';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."ANOUNCEMENT" IS 'The anouncement will be displayed as a startpoint to the subscribtion-page';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."GBR_KEY" IS 'Foreign Key to the user-table. The e-mail address of the user can be set';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."LASTNAME_SUBSCRIBER" IS 'Lastname of the subscriber';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."FIRSTNAME_SUBSCRIBER" IS 'Firstname of the subscriber';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."MIDDELNAME_SUBSCRIBER" IS 'Middlename of the subscriber';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."EMAIL_SUBSCRIBER" IS 'E-mail address of the subscriber';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."PHONE_SUBSCRIBER" IS 'Phonenumber of the subscriber';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."TITLE" IS 'Title of the subscritions as will be displayed above the anouncement';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."STARTDATE" IS 'The begindate of the subscribtion';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."ENDDATE" IS 'The enddate of the subscribtion';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."DATE_CREATED" IS 'The date of creation';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."ARCHIVE" IS 'Is the record put in archive';
  COMMENT ON COLUMN "BSM_SUBSCRIPTIONS"."LANGUAGE" IS 'The language of this subscription';

  CREATE TABLE "DEELNEMERS" 
  ( "VOLGNR" NUMBER(11,0)
  , "ACHTERNAAM" VARCHAR2(100 BYTE) DEFAULT NULL
  , "TUSSENVOEGSEL" VARCHAR2(50 BYTE) DEFAULT NULL
  , "VOORNAAM" VARCHAR2(50 BYTE) DEFAULT NULL
  , "POSITIES" VARCHAR2(50 BYTE) DEFAULT NULL
  , "TEM_VOLGNR" NUMBER(11,0) DEFAULT NULL
  , "SDS_VOLGNR" NUMBER(11,0) DEFAULT NULL
  , "FOTO" VARCHAR2(1000 BYTE)
  , "RUGNUMMER" NUMBER(11,0)
  , "GEBOORTEDATUM" DATE
  , "LIDNUMMER" VARCHAR2(10 BYTE)
  , "STRAATNAAM" VARCHAR2(200 BYTE)
  , "HUISNUMMER" VARCHAR2(10 BYTE)
  , "POSTCODE" VARCHAR2(6 BYTE)
  , "PLAATS" VARCHAR2(200 BYTE)
  , "TELEFOON" VARCHAR2(12 BYTE)
  , "ALTERNATIEFMOB" VARCHAR2(12 BYTE)
  , "EMAIL" VARCHAR2(500 BYTE)
  , "BEGINDATUMLID" DATE
  , "TEST" VARCHAR2(20 BYTE)
  , CONSTRAINT "DNSPK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "DNS_SDS_FK" FOREIGN KEY ("SDS_VOLGNR") REFERENCES "SOORT_DEELNEMERS" ("VOLGNR") ENABLE
  );

  COMMENT ON TABLE "DEELNEMERS"  IS 'Huidige leden tabel (spelers)';

  CREATE TABLE "GASTENBOEK" 
  ( "VOLGNR" NUMBER(11,0)
  , "OPMERKING" VARCHAR2(2000 BYTE) DEFAULT NULL
  , "NAAM" VARCHAR2(255 BYTE) DEFAULT NULL
  , "EMAIL" VARCHAR2(255 BYTE) DEFAULT NULL
  , "HOMEPAGENAAM" VARCHAR2(255 BYTE) DEFAULT NULL
  , "HOMEPAGE" VARCHAR2(255 BYTE) DEFAULT NULL
  , "TYPE_GASTENBOEK" NUMBER(11,0) DEFAULT NULL
  , "DATUM" DATE DEFAULT NULL
  , CONSTRAINT "GTK_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "GTK_TGK_FK" FOREIGN KEY ("TYPE_GASTENBOEK") REFERENCES "TYPE_GASTENBOEK" ("VOLGNR") ENABLE
  );

  COMMENT ON TABLE "GASTENBOEK"  IS 'Gastenboek';

  CREATE TABLE "INFO" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "TITEL" VARCHAR2(60 BYTE) DEFAULT NULL
  , "TITEL_EN" VARCHAR2(60 BYTE) DEFAULT NULL
  , "BERICHT" CLOB
  , "BERICHT_EN" CLOB
  , "PLAATJE" VARCHAR2(100 BYTE) DEFAULT NULL
  , "DATUM_BERICHT" DATE DEFAULT NULL
  , "EINDDATUM_BERICHT" DATE DEFAULT NULL
  , "GBR_VOLGNR" NUMBER(11,0) DEFAULT NULL
  , "TYPE_INFO" NUMBER(11,0) DEFAULT NULL
  , "PGA_VOLGNR" NUMBER(11,0) DEFAULT NULL
  , "PGA_EN_VOLGNR" NUMBER(11,0) DEFAULT NULL
  , "URL" VARCHAR2(255 BYTE) DEFAULT NULL
  , "URL_OMSCHRIJVING" VARCHAR2(255 BYTE) DEFAULT NULL
  , "URL_OMSCHRIJVING_EN" VARCHAR2(255 BYTE) DEFAULT NULL
  , "URL_EN" VARCHAR2(255 BYTE) DEFAULT NULL
  , "DISPLAY_VOLGNR" NUMBER(11,0) DEFAULT NULL
  , "TOON_OP_HOMEPAGE" VARCHAR2(1 BYTE) DEFAULT NULL
  , "ARCHIEF" VARCHAR2(1 BYTE)
  , "DATUM_GEWIJZIGD" DATE
  , "GBR_VOLGNR_GEWIJZIGD" NUMBER(11,0)
  , "AUTO_ARCHIEF" VARCHAR2(1 BYTE)
  , "VERMELD_AUTEUR" VARCHAR2(1 BYTE)
  , "INLEIDING" CLOB
  , "INLEIDING_EN" CLOB
  , CONSTRAINT "IFO_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "IFO_TIO_FK" FOREIGN KEY ("TYPE_INFO") REFERENCES "TYPE_INFO" ("VOLGNR") ENABLE
  );

  COMMENT ON TABLE "INFO"  IS 'Informatie Items';

  CREATE TABLE "WEDSTRIJDEN" 
  ( "VOLGNR" NUMBER(11,0) NOT NULL ENABLE
  , "DATUM" DATE DEFAULT NULL
  , "THUIS_UIT" VARCHAR2(1 BYTE) DEFAULT NULL
  , "TEGENSTANDER" VARCHAR2(100 BYTE) DEFAULT NULL
  , "TIJDSTIP" VARCHAR2(10 BYTE) DEFAULT NULL
  , "PUNTEN_VOOR" VARCHAR2(10 BYTE) DEFAULT NULL
  , "PUNTEN_TEGEN" VARCHAR2(10 BYTE) DEFAULT NULL
  , "TEAM_VOLGNR" NUMBER(11,0) DEFAULT NULL
  , "SOORT" VARCHAR2(3 BYTE) DEFAULT NULL
  , "TEAM_NAAM" VARCHAR2(100 BYTE) DEFAULT NULL
  , "OPMERKING" VARCHAR2(50 BYTE) DEFAULT NULL
  , "TYPE_WEDSTRIJD" VARCHAR2(10 BYTE) DEFAULT NULL
  , "SCHEIDSRECHTERS" VARCHAR2(100 BYTE)
  , "WEDSTRIJD_NUMMER" VARCHAR2(10 BYTE)
  , "ARCHIEF" VARCHAR2(1 BYTE)
  , "VELD_INFO" NUMBER(12,0)
  , "AFGELAST" VARCHAR2(1 BYTE)
  , CONSTRAINT "WSD_PK" PRIMARY KEY ("VOLGNR") USING INDEX ENABLE
  , CONSTRAINT "WSD_SLE_FK" FOREIGN KEY ("VELD_INFO") REFERENCES "BSM_SPEELLOKATIES" ("VOLGNR") ENABLE
  , CONSTRAINT "WSD_TEM_FK" FOREIGN KEY ("TEAM_VOLGNR") REFERENCES "TEAMS" ("VOLGNR") ENABLE
  );

  COMMENT ON TABLE "WEDSTRIJDEN"  IS 'Wedstrijden';

  CREATE TABLE "BSM_MIJN_DOCUMENTS" 
  (	"VOLGNR" NUMBER(10,0) NOT NULL ENABLE
  , "NAAM" VARCHAR2(1000 CHAR) NOT NULL ENABLE
  , "DIRECTORY" VARCHAR2(1 CHAR)
  , "MDS_VOLGNR" NUMBER(10,0)
  , "OMSCHRIJVING" VARCHAR2(2000 CHAR)
  , "TYPE" VARCHAR2(500 CHAR)
  , "OPSLAGNAAM" VARCHAR2(1000 CHAR)
  , "GBR_VOLGNR" NUMBER(10,0)
  , "DATUM_AANGEMAAKT" DATE
  , "PUBLISHED" VARCHAR2(1 BYTE)
  , CONSTRAINT "MDS_PK" PRIMARY KEY ("VOLGNR")  USING INDEX ENABLE
  , CONSTRAINT "MDS_MDS_FK" FOREIGN KEY ("MDS_VOLGNR") REFERENCES "BSM_MIJN_DOCUMENTS" ("VOLGNR") ENABLE
  );

  COMMENT ON COLUMN "BSM_MIJN_DOCUMENTS"."DIRECTORY" IS 'J of N';
 
  COMMENT ON COLUMN "BSM_MIJN_DOCUMENTS"."MDS_VOLGNR" IS 'mogelijke parent';
 
  COMMENT ON COLUMN "BSM_MIJN_DOCUMENTS"."OMSCHRIJVING" IS 'omschrijving';
 
  COMMENT ON COLUMN "BSM_MIJN_DOCUMENTS"."TYPE" IS 'type';
