--------------------------------------------------------
--  SEQUENCES
--------------------------------------------------------

   CREATE SEQUENCE  "ALS_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "APT_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "BEZOEKERS_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 175234 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "BHM_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "BRT_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 49 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "BSM_DCT_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 2192 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "CDL_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 209 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "CIE_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "DCE_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 16 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "DNR_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1777 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "DOC_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 55 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "FUN_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 294 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "GBK_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1771 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "GBR_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 280 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "INFO_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1666 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "IPA_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 119 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "KLR_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 533 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "LCE_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "LDN_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "LOGIN_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 11903 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "MDS_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 84 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "RGR_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 405 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "SSN_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "TAS_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "TEM_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 44 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "TIO_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 85 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "TLD_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE ;

   CREATE SEQUENCE  "WED_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 6386 NOCACHE  NOORDER  NOCYCLE ;
