-- ------------------------------------------------------
--  TABLES
-- ------------------------------------------------------
USE homeplate;

CREATE TABLE `BSM_SYSVAR` 
( `CODE` VARCHAR(50)
, `WAARDE` VARCHAR(100)
, `OMSCHRIJVING` VARCHAR(250)
, `TOON_VOLGNR` SMALLINT
, CONSTRAINT `SVR_KEY` PRIMARY KEY (`CODE`)
);

ALTER TABLE `BSM_SYSVAR`  COMMENT 'Systeem variabelen';

CREATE TABLE `BSM_DISC_GROEPEN` 
( `VOLGNR` BIGINT NOT NULL 
, `NAAM` VARCHAR(50), `OMSCHRIJVING` VARCHAR(500)
, CONSTRAINT `DGP_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `BSM_DISC_GROEPEN`  COMMENT 'Discussiegroepen';

CREATE TABLE `BSM_DOC_HIERARCHIEEN` 
( `DHE_VOLGNR` BIGINT NOT NULL 
, `NAAM` VARCHAR(2000) NOT NULL 
, `DATUM_OPNAME` DATE NOT NULL 
, `INFO` VARCHAR(4000)
, `DHE_DHE_VOLGNR` BIGINT
, CONSTRAINT `DHE_PK` PRIMARY KEY (`DHE_VOLGNR`)
);

CREATE TABLE `BSM_DOC_INFO` 
( `DCT_VOLGNR` BIGINT NOT NULL 
, `NAAM` VARCHAR(2000) NOT NULL 
, `GROOTTE` BIGINT, `DATUM` DATE NOT NULL 
, `DATUM_OPNAME` DATE
, `DATUM_GERAADPLEEGD` DATE
, `INFO` VARCHAR(4000)
, CONSTRAINT `DCT_PK` PRIMARY KEY (`DCT_VOLGNR`)
);

CREATE TABLE `BSM_DOC_LABELS` 
( `DLL_VOLGNR` BIGINT NOT NULL 
, `LABEL` VARCHAR(50) NOT NULL 
, `INCL_SUBDIRECTORIES` VARCHAR(1)
);

CREATE INDEX `BSM_DLL_LABEL_IDX` ON `BSM_DOC_LABELS` (`LABEL`) 
;

CREATE TABLE `BSM_DOCUMENTEN` 
( `NAME` VARCHAR(256) NOT NULL 
, `MIME_TYPE` VARCHAR(128), `DOC_SIZE` DOUBLE
, `DAD_CHARSET` VARCHAR(128)
, `LAST_UPDATED` DATE
, `CONTENT_TYPE` VARCHAR(128)
, `CONTENT` LONGBLOB
, `BLOB_CONTENT` LONGBLOB
, `DCE_VOLGNR` BIGINT
, `BLOB_CONTENT_THUMBNAIL` LONGBLOB
, CONSTRAINT `DCN_KEY` PRIMARY KEY (`NAME`)
);

CREATE TABLE `BSM_GROEPEN` 
( `GRP_VOLGNR` BIGINT
, `OMSCHRIJVING` VARCHAR(100)
);

CREATE TABLE `BSM_DOCUMENT_TYPE` 
( `DCE_VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(500)
, `FOTOALBUM` VARCHAR(1)
, CONSTRAINT `DCE_PK` PRIMARY KEY (`DCE_VOLGNR`)
);

CREATE TABLE `BSM_ERRORLOG` 
( `DATUM` DATE
, `ONDERDEEL` VARCHAR(500)
, `SQL_CODE` VARCHAR(500)
, `SQL_ERRMSG` VARCHAR(2000)
, `GEBRUIKER` VARCHAR(200)
, `ADDITIONEEL` VARCHAR(2000)
);

CREATE TABLE `BSM_EVENTS` 
( `VOLGNR` BIGINT NOT NULL 
, `TITEL` VARCHAR(100) NOT NULL 
, `OMSCHRIJVING` VARCHAR(2000)
, `BEGINDATUM` DATE
, `EINDDATUM` DATE
, `LOCATIE` VARCHAR(200)
, CONSTRAINT `EVT_PK` PRIMARY KEY (`VOLGNR`)
);

CREATE TABLE `BSM_FILE_TYPEN` 
( `FTE_VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(50) NOT NULL 
, `ICON_BESTAND` VARCHAR(50) NOT NULL 
, `EXTENTIE` VARCHAR(10) NOT NULL 
, CONSTRAINT `FTE_1_PK` PRIMARY KEY (`FTE_VOLGNR`)
);

CREATE TABLE `BSM_GEBRUIKERS` 
( `GBR_VOLGNR` BIGINT
, `LOGINNAAM` VARCHAR(50)
, `VOORNAAM` VARCHAR(25)
, `VOORVOEGSEL` VARCHAR(15)
, `ACHTERNAAM` VARCHAR(50)
, `ADRES` VARCHAR(100)
, `POSTCODE` VARCHAR(6)
, `WOONPLAATS` VARCHAR(100)
, `TELEFOON_PRIVE` VARCHAR(11)
, `MOBIEL_NUMMER` VARCHAR(11)
, `GEBOORTEDATUM` DATE
, `DATUM_INDIENST` DATE
, `DATUM_UITDIENST` DATE
, `GRP_VOLGNUMMER` SMALLINT
, CONSTRAINT `GBS_PK` PRIMARY KEY (`GBR_VOLGNR`)
);

CREATE TABLE `BSM_IDEEEN` 
( `VOLGNR` BIGINT
, `OPMERKING` VARCHAR(255)
, `NAAM` VARCHAR(255)
, `EMAIL` VARCHAR(255)
, `HOMEPAGENAAM` VARCHAR(255)
, `HOMEPAGE` VARCHAR(255)
, `DATUM` DATE
, `TYPE_IDEEEN` BIGINT
, `GBR_VOLGNR` BIGINT
, CONSTRAINT `IDN_PK` PRIMARY KEY (`VOLGNR`)
);

CREATE TABLE `BSM_KALENDER` 
( `VOLGNR` BIGINT NOT NULL 
, `DATUM` DATE
, `TITEL` VARCHAR(100)
, `OMSCHRIJVING` VARCHAR(2000)
, CONSTRAINT `KLR_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `BSM_KALENDER`  COMMENT 'Kalender';

CREATE TABLE `INFO_PAGINAS` 
( `VOLGNR` BIGINT NOT NULL 
, `INHOUD` LONGTEXT
,  CONSTRAINT `IPS_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `INFO_PAGINAS`  COMMENT 'Informatie Paginas';

CREATE TABLE `MAILBERICHT` 
( `VOLGNR` BIGINT NOT NULL 
, `ONDERWERP` VARCHAR(500)
, `BERICHTTEKST` VARCHAR(4000)
, `ADRES` VARCHAR(1000)
, `DATUM_BERICHT` DATE
, `GBRVOLGNR` BIGINT NOT NULL 
, `DATUM_VERWERKT` DATE
, `STATUS` VARCHAR(1)
);

CREATE TABLE `MAILGEBRUIKERS` 
( `VOLGNR` BIGINT NOT NULL 
, `LOGINID` VARCHAR(100)
, `WACHTWOORD` VARCHAR(100)
, `VOORNAAM` VARCHAR(100)
, `TUSSENVOEGSEL` VARCHAR(100)
, `ACHTERNAAM` VARCHAR(100)
, `TEMVOLGNR` BIGINT
, `SESSION_ID` VARCHAR(100)
);

CREATE TABLE `BSM_LOGIN` 
( `GBR_VOLGNR` DOUBLE
, `DATUM` DATE
);

ALTER TABLE `BSM_LOGIN`  COMMENT 'Login informatie';

CREATE TABLE `MAILTEAMS` 
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(100)
);

CREATE TABLE `SOORT_DEELNEMERS` 
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(50) DEFAULT NULL
,  CONSTRAINT `SDS_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `SOORT_DEELNEMERS`  COMMENT 'Soort deelnemers (spelers)';

CREATE TABLE `TEAMS` 
( `VOLGNR` BIGINT NOT NULL 
, `NAAM` VARCHAR(50) DEFAULT NULL
, `KLASSE` VARCHAR(100) DEFAULT NULL
, `SOORT` VARCHAR(10) DEFAULT NULL
, `HOMEPAGE` VARCHAR(100) DEFAULT NULL
, `FOTO` VARCHAR(100) DEFAULT NULL
, `GEBRUIKERSID` VARCHAR(50) DEFAULT NULL
, `DISPLAY_VOLGNR` BIGINT
, `VRIJETEKST` LONGTEXT
, `SPONSORNAAM` VARCHAR(200)
, `SPONSORFOTO` VARCHAR(100)
, `SPONSORURL` VARCHAR(100)
, `STANDURL` VARCHAR(100)
, `HOOFDTEAM` VARCHAR(1)
, CONSTRAINT `TEM_PK` PRIMARY KEY (`VOLGNR`) 
); 

ALTER TABLE `TEAMS`  COMMENT 'Teams';

CREATE TABLE `TYPE_GASTENBOEK` 
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(50) DEFAULT NULL
, CONSTRAINT `TGK_PK` PRIMARY KEY (`VOLGNR`)
); 

ALTER TABLE `TYPE_GASTENBOEK`  COMMENT 'Type Gastenboek';

CREATE TABLE `BSM_FUNCTIES` 
( `FUN_VOLGNR` BIGINT NOT NULL 
, `NAAM_FUNCTIE` VARCHAR(50)
, `OMSCHRIJVING_FUNCTIE` VARCHAR(2000)
, `NIVO_MENU` TINYINT NOT NULL 
, `URL` VARCHAR(100)
, `FUN_VOLGNR_FK` BIGINT
, `TOON_VOLGNR` BIGINT
, `PLAATJE` VARCHAR(50)
, `TYPE_INFO_VOLGNR` BIGINT
, `NAAM_FUNCTIE_EN` VARCHAR(50)
, `OMSCHRIJVING_FUNCTIE_EN` VARCHAR(2000)
, `DOCUMENT_VOLGNR` BIGINT
, `TYPE` VARCHAR(50)
, `TARGET` VARCHAR(100)
, `FOTOALBUM_VOLGNR` BIGINT
, CONSTRAINT `FUNPK` PRIMARY KEY (`FUN_VOLGNR`)
);

ALTER TABLE `BSM_FUNCTIES`  COMMENT 'Functies menuingangen website';

CREATE TABLE `BSM_GBR_GRP` 
( `GBR_VOLGNUMMER` BIGINT
, `GRP_VOLGNUMMER` BIGINT
);

CREATE TABLE `TYPE_INFO` 
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(50) DEFAULT NULL
, `OMSCHRIJVING_EN` VARCHAR(50) DEFAULT NULL
, `ARCHIEF` VARCHAR(1)
, `LAATSTE_UPDATE` DATE
, CONSTRAINT `TIO_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `TYPE_INFO`  COMMENT 'Type Informatie paginas';

CREATE TABLE `BSM_DISC_NEW` 
( `GBR_VOLGNR` BIGINT
, `DISC_SOORT` VARCHAR(3)
, `DISC_VOLGNR` BIGINT
, `DATUM` DATE
);

CREATE TABLE `BSM_LINK_EIGENAAR` 
( `VOLGNR` SMALLINT NOT NULL 
, `GEBRUIKERSID` VARCHAR(20) NOT NULL 
, `WACHTWOORD` VARCHAR(20) NOT NULL 
, `VOORNAAM` VARCHAR(50)
, `TUSSENVOEGSEL` VARCHAR(20)
, `ACHTERNAAM` VARCHAR(50)
);

CREATE TABLE `BSM_LINKGROEP` 
( `VOLGNR` SMALLINT NOT NULL 
, `GROEPNAAM` VARCHAR(100) NOT NULL 
, `OMSCHRIJVING` VARCHAR(500)
, `DISPLAY_VOLGNR` SMALLINT
, `EIGENAAR_VOLGNR` SMALLINT NOT NULL 
);

CREATE TABLE `BSM_LINKS` 
( `VOLGNR` BIGINT NOT NULL 
, `TITEL` VARCHAR(100) NOT NULL 
, `URL` VARCHAR(500) NOT NULL 
, `OMSCHRIJVING` VARCHAR(500)
, `GROEP_VOLGNR` SMALLINT
, `EIGENAAR_VOLGNR` SMALLINT
);

CREATE TABLE `BSM_MUTATIES` 
( `SOORT` VARCHAR(10)
, `KEY_SOORT` BIGINT
, `DATUM` DATE
, `GBR_VOLGNR` BIGINT
, `MUTATIE_TYPE` VARCHAR(10)
); 

ALTER TABLE `BSM_MUTATIES`  COMMENT 'Gebruikt voor bijhouden mutaties op wedstrijden';

CREATE TABLE `BSM_SECURITY` 
( `DATUM` DATE
, `CAMERA` VARCHAR(1)
);

CREATE TABLE `BSM_SMOELEN` 
( `SML_VOLGNR` BIGINT
, `PLAATJE` VARCHAR(100)
, `GBR_VOLGNUMMER` BIGINT
);

CREATE TABLE `BSM_SPEELLOKATIES` 
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(200) NOT NULL 
,  CONSTRAINT `SLE_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `BSM_SPEELLOKATIES`  COMMENT 'Lokaties waarop gespeeld kan worden';

CREATE TABLE `BSM_SPONSOR_LOGOS` 
( `VOLGNR` BIGINT NOT NULL 
, `TITEL` VARCHAR(50)
, `URL` VARCHAR(100)
, `BESTANDSNAAM` VARCHAR(100)
, `DISPLAY_VOLGNR` BIGINT
, `TONEN_IN_CARROUSSEL` VARCHAR(3)
, CONSTRAINT `SLS_PK` PRIMARY KEY (`VOLGNR`)
);

CREATE TABLE `BSM_SYSTEEM_MEDEDELING` 
( `VOLGNR` BIGINT NOT NULL 
, `DATUM` DATE NOT NULL 
, `MEDEDELING` VARCHAR(4000)
, `TYPE` VARCHAR(50)
, `ACTIEF` VARCHAR(1)
, `OMSCHRIJVING` VARCHAR(100)
); 

ALTER TABLE `BSM_SYSTEEM_MEDEDELING`  COMMENT 'Systeem mededelingen Oracle beheer';

CREATE TABLE `BSM_TEM_GBR` 
( `TEM_VOLGNR` BIGINT NOT NULL 
, `GBR_VOLGNR` BIGINT NOT NULL 
, CONSTRAINT `TEMGBR_PK` PRIMARY KEY (`TEM_VOLGNR`, `GBR_VOLGNR`)
); 

ALTER TABLE `BSM_TEM_GBR`  COMMENT 'Teambeheerders';

CREATE TABLE `BSM_TRAININGSTIJD` 
( `TEM_VOLGNR` BIGINT NOT NULL 
, `ZO_TIJD` VARCHAR(10)
, `MA_TIJD` VARCHAR(10)
, `DI_TIJD` VARCHAR(10)
, `WO_TIJD` VARCHAR(10)
, `DO_TIJD` VARCHAR(10)
, `VR_TIJD` VARCHAR(10)
, `ZA_TIJD` VARCHAR(10)
, `ZO_LOK` VARCHAR(200)
, `MA_LOK` VARCHAR(200)
, `DI_LOK` VARCHAR(200)
, `WO_LOK` VARCHAR(200)
, `DO_LOK` VARCHAR(200)
, `VR_LOK` VARCHAR(200)
, `ZA_LOK` VARCHAR(200)
, CONSTRAINT `BSM_TRAININGSTIJD_PK` PRIMARY KEY (`TEM_VOLGNR`)
);

ALTER TABLE `BSM_TRAININGSTIJD`  COMMENT 'Trainingen';

CREATE TABLE `BSM_TYPE_LEDEN` 
( `VOLGNR` BIGINT NOT NULL 
, `CODE` VARCHAR(10) NOT NULL 
, `OMSCHRIJVING` VARCHAR(100) NOT NULL 
, CONSTRAINT `TLD_PK` PRIMARY KEY (`VOLGNR`)
);  

ALTER TABLE `BSM_TYPE_LEDEN`  COMMENT 'Type Leden';

CREATE TABLE `BSM_TYPE_TEAMS` 
( `CODE` VARCHAR(10) NOT NULL 
, `OMSCHRIJVING` VARCHAR(100) NOT NULL 
, `DISPLAY_VOLGNR` SMALLINT
, `OMSCHRIJVING_EN` VARCHAR(100)
, CONSTRAINT `TTS_PK` PRIMARY KEY (`CODE`)
);

ALTER TABLE `BSM_TYPE_TEAMS`  COMMENT 'Type Teams';

CREATE TABLE `DOCUMENTEN` 
( `VOLGNR` BIGINT NOT NULL 
, `INHOUD` LONGTEXT
, `TITEL` VARCHAR(100) NOT NULL 
, `DATUM_TOEGEVOEGD` DATE
, `ARCHIEF` VARCHAR(1)
, `TAAL` VARCHAR(2) NOT NULL 
, `SITE_STYLE` VARCHAR(1)
);

CREATE TABLE `BSM_ROL_GBR` 
( `GBR_VOLGNR` BIGINT
, `ROL_VOLGNR` BIGINT
, `VOLGNR` BIGINT
, CONSTRAINT `RGR_PK` PRIMARY KEY (`VOLGNR`)
);

CREATE TABLE `BSM_EMAILADRES` 
( `VOLGNR` BIGINT NOT NULL 
, `EMAILADRES` VARCHAR(100) NOT NULL 
, `OMSCHRIJVING` VARCHAR(100)
, CONSTRAINT `EMS_PK` PRIMARY KEY (`VOLGNR`)
);

CREATE TABLE `BSM_EMAILFORWARDS` 
( `VOLGNR` BIGINT NOT NULL 
, `EML_VOLGNR` BIGINT NOT NULL 
, `EMAILADRES` VARCHAR(100)
, `NAAM` VARCHAR(100)
, CONSTRAINT `EMD_PK` PRIMARY KEY (`VOLGNR`)
, CONSTRAINT `EMD_EMS_FK` FOREIGN KEY (`EML_VOLGNR`) REFERENCES `BSM_EMAILADRES` (`VOLGNR`) 
);

CREATE TABLE `GEBRUIKERS` 
( `VOLGNR` BIGINT NOT NULL 
, `GEBRUIKERSID` VARCHAR(50) NOT NULL 
, `ACHTERNAAM` VARCHAR(50)
, `TUSSENVOEGSEL` VARCHAR(50)
, `VOORNAAM` VARCHAR(50)
, `WACHTWOORD` VARCHAR(50)
, `SESSION_ID` VARCHAR(50)
, `DATUM_INLOG` DATE
, `DATUM_UITLOG` DATE
, `TYPE_GEBRUIKER` VARCHAR(10)
, `INITIALEN` VARCHAR(10)
, `EMAIL` VARCHAR(100)
, `TELEFOONNUMMER` VARCHAR(20)
, `STATUS` VARCHAR(50)
, `LIDNUMMER` VARCHAR(10)
, `GEBOORTEDATUM` DATE
, `REGISTREERSID` VARCHAR(50)
, `PAPIEREN_NIEUWS` VARCHAR(1)
, `PELLIKAAN_AL_LID` VARCHAR(1)
, `PELLIKAAN_MEEDOEN` VARCHAR(1)
, CONSTRAINT `GBR_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `GEBRUIKERS`  COMMENT 'Gebruikers beheer';

CREATE TABLE `BSM_AANMELDINGEN` 
( `VOLGNR` BIGINT NOT NULL 
, `EVT_VOLGNR` BIGINT NOT NULL 
, `ACHTERNAAM` VARCHAR(100) NOT NULL 
, `TUSSENVOEGSEL` VARCHAR(20)
, `VOORNAAM` VARCHAR(50)
, `STRAATNAAM` VARCHAR(100)
, `HUISNUMMER` VARCHAR(20)
, `POSTCODE` VARCHAR(20)
, `PLAATS` VARCHAR(100)
, `TELEFOON` VARCHAR(12)
, `MOBIEL` VARCHAR(12)
, `EMAIL` VARCHAR(100)
, `GEBOORTEDATUM` DATE
, `EXTRA1` VARCHAR(2000)
, `EXTRA2` VARCHAR(2000)
, `EXTRA3` VARCHAR(2000)
, `EXTRA4` VARCHAR(2000)
, `EXTRA5` VARCHAR(2000)
, `EXTRA6` VARCHAR(2000)
, `AANTAL_INTRODUCEES` TINYINT
, `AANTAL_INTROD_REUNIE` TINYINT
, CONSTRAINT `AMG_PK` PRIMARY KEY (`VOLGNR`)
, CONSTRAINT `AMG_EVT_FK` FOREIGN KEY (`EVT_VOLGNR`) REFERENCES `BSM_EVENTS` (`VOLGNR`) 
);

CREATE TABLE `BSM_TYPEAKTIES`
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(500) NOT NULL 
, CONSTRAINT `TAE_PK` PRIMARY KEY (`VOLGNR`)
);

CREATE TABLE `BSM_AKTIEPUNTEN` 
(`VOLGNR` BIGINT NOT NULL 
, `AKTIEPUNT` VARCHAR(500) NOT NULL 
, `OMSCHRIJVING` VARCHAR(1000)
, `STATUS` VARCHAR(1)
, `AANMAAKDATUM` DATE
, `WIJZIGDATUM` DATE
, `TYPE_AKTIE` BIGINT
,  CONSTRAINT `ATE_PK` PRIMARY KEY (`VOLGNR`)
,  CONSTRAINT `ATE_TAE_FK` FOREIGN KEY (`TYPE_AKTIE`) REFERENCES `BSM_TYPEAKTIES` (`VOLGNR`) 
);

ALTER TABLE `BSM_AKTIEPUNTEN`  COMMENT 'Aktiepunten';

CREATE TABLE `BSM_AKTIE_LOGS` 
( `VOLGNR` BIGINT NOT NULL 
, `DATUM` DATE NOT NULL 
, `AKE_VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(4000)
,  CONSTRAINT `ALG_PK` PRIMARY KEY (`VOLGNR`)
,  CONSTRAINT `ALG_AKE_FK` FOREIGN KEY (`AKE_VOLGNR`) REFERENCES `BSM_AKTIEPUNTEN` (`VOLGNR`) 
);

ALTER TABLE `BSM_AKTIE_LOGS`  COMMENT 'Aktiepunten Logs';

CREATE TABLE `BSM_BEHEER_MODULES` 
( `VOLGNR` BIGINT NOT NULL 
, `MODULENAAM` VARCHAR(100)
, `MODULEID` VARCHAR(100)
, `NIVO` SMALLINT
, `FOLDERNAAM` VARCHAR(100)
, `BMS_VOLGNR` SMALLINT
, `DISPLAY_VOLGNR` SMALLINT
, CONSTRAINT `BMS_PK` PRIMARY KEY (`VOLGNR`)
);

ALTER TABLE `BSM_BEHEER_MODULES`  COMMENT 'BeheerModules java';

CREATE TABLE `BSM_ROLLEN` 
( `ROL_VOLGNR` BIGINT
, `ROLNAAM` VARCHAR(50)
, CONSTRAINT `ROL_PK` PRIMARY KEY (`ROL_VOLGNR`)
);

ALTER TABLE `BSM_ROLLEN`  COMMENT 'Rollen beheer Oracle';
 
CREATE TABLE `BSM_BMS_ROL` 
( `VOLGNR` BIGINT NOT NULL 
, `ROL_VOLGNR` BIGINT NOT NULL 
, `BMS_VOLGNR` BIGINT NOT NULL 
,  CONSTRAINT `BRL_PK` PRIMARY KEY (`VOLGNR`)
,  CONSTRAINT `BRL_BMS_FK` FOREIGN KEY (`BMS_VOLGNR`) REFERENCES `BSM_BEHEER_MODULES` (`VOLGNR`) 
,  CONSTRAINT `BRL_ROL_FK` FOREIGN KEY (`ROL_VOLGNR`) REFERENCES `BSM_ROLLEN` (`ROL_VOLGNR`) 
); 

ALTER TABLE `BSM_BMS_ROL`  COMMENT 'Beheermodules per rol';

CREATE TABLE `BSM_FUN_ROL` 
( `FUN_VOLGNR` BIGINT
, `ROL_VOLGNR` BIGINT
);

CREATE TABLE `BSM_CIES` 
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(100) NOT NULL 
, `ARCHIEF` VARCHAR(1) NOT NULL 
);

ALTER TABLE `BSM_CIES`  COMMENT 'Commissies';

CREATE TABLE `BSM_TYPE_CONDOLEANCE` 
( `VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(50)
, `FOTO` VARCHAR(1000)
, `TEKST` VARCHAR(4000)
, `TEKST_EN` VARCHAR(4000)
, `FOTO_WIDTH` VARCHAR(4)
, `FOTO_HEIGHT` VARCHAR(4)
);

ALTER TABLE `BSM_TYPE_CONDOLEANCE`  COMMENT 'Type condoleances';

CREATE TABLE `BSM_CONDOLEANCE` 
( `VOLGNR` BIGINT NOT NULL 
, `OPMERKING` VARCHAR(2000)
, `NAAM` VARCHAR(255)
, `TYPE_CONDOLEANCE` BIGINT
, `DATUM` DATE
);

ALTER TABLE `BSM_CONDOLEANCE`  COMMENT 'Condoleance register';

CREATE TABLE `BSM_DISC_TOPICS` 
( `VOLGNR` BIGINT NOT NULL 
, `ONDERWERP` VARCHAR(100)
, `OMSCHRIJVING` VARCHAR(2000)
, `DATUM` DATE
, `DGP_VOLGNR` BIGINT NOT NULL 
, `GBR_VOLGNR` BIGINT NOT NULL 
, CONSTRAINT `DTC_PK` PRIMARY KEY (`VOLGNR`)
, CONSTRAINT `DTC_DGP_FK` FOREIGN KEY (`DGP_VOLGNR`) REFERENCES `BSM_DISC_GROEPEN` (`VOLGNR`) 
, CONSTRAINT `DTC_GBR_FK` FOREIGN KEY (`GBR_VOLGNR`) REFERENCES `GEBRUIKERS` (`VOLGNR`) 
);

CREATE TABLE `BSM_DISC_REACTIES` 
( `VOLGNR` BIGINT NOT NULL 
, `ONDERWERP` VARCHAR(100)
, `OMSCHRIJVING` VARCHAR(2000)
, `DATUM` DATE
, `DTC_VOLGNR` BIGINT NOT NULL 
, `GBR_VOLGNR` BIGINT NOT NULL 
,  CONSTRAINT `DRE_PK` PRIMARY KEY (`VOLGNR`)
,  CONSTRAINT `DRE_DTC_FK` FOREIGN KEY (`DTC_VOLGNR`) REFERENCES `BSM_DISC_TOPICS` (`VOLGNR`) 
,  CONSTRAINT `DRE_GBR_FK` FOREIGN KEY (`GBR_VOLGNR`) REFERENCES `GEBRUIKERS` (`VOLGNR`) 
);

CREATE TABLE `BSM_DOC_DCE` 
( `DCE_VOLGNR` BIGINT NOT NULL 
, `DOC_VOLGNR` BIGINT NOT NULL 
, CONSTRAINT `DCEDOC_PK` PRIMARY KEY (`DCE_VOLGNR`, `DOC_VOLGNR`)
, CONSTRAINT `DCEDOC_DCE_FK` FOREIGN KEY (`DCE_VOLGNR`) REFERENCES `BSM_DOCUMENT_TYPE` (`DCE_VOLGNR`) 
, CONSTRAINT `DCEDOC_DOC_FK` FOREIGN KEY (`DOC_VOLGNR`) REFERENCES `BSM_DOC_INFO` (`DCT_VOLGNR`) 
);

CREATE TABLE `BSM_LEDEN` 
( `VOLGNR` BIGINT NOT NULL 
, `ACHTERNAAM` VARCHAR(100)
, `VOORNAAM` VARCHAR(50)
, `TUSSENVOEGSEL` VARCHAR(20)
, `LIDNR` VARCHAR(10)
, `STRAATNAAM` VARCHAR(100)
, `HUISNUMMER` VARCHAR(50)
, `POSTCODE` VARCHAR(7)
, `WOONPLAATS` VARCHAR(100)
, `TELEFOON` VARCHAR(13)
, `MOBIEL` VARCHAR(13)
, `EMAIL` VARCHAR(100)
, `GEBOORTEDATUM` DATE
, `BEGINDATUM_LID` DATE
, `EINDDATUM_LID` DATE
, `TLD_VOLGNR` BIGINT
, `AANHEF` VARCHAR(10)
, `VOORLETTERS` VARCHAR(15)
, `TOEVOEGING_ADRES` VARCHAR(50)
, `GEBOORTEPLAATS` VARCHAR(100)
, `NATIONALITEIT` VARCHAR(50)
, `GESLACHT` VARCHAR(4)
, `MUTATIE_DATUM` DATE
, `REDEN_MUTATIE` VARCHAR(100)
, `SOORT_LID` VARCHAR(20)
, `SOORT_LID_BOND` VARCHAR(20)
, `SPELEND_LID` VARCHAR(1)
, `NIET_SPELEND_LID` VARCHAR(1)
, `TEAM_99` VARCHAR(20)
, `TR_CO` VARCHAR(50)
, `BEGELEIDER` VARCHAR(50)
, `DONATEUR` VARCHAR(1)
, `KADERLID` VARCHAR(1)
, `ADVERTEERDER` VARCHAR(1)
, `LVV` VARCHAR(1)
, `JAAR_LVV` VARCHAR(4)
, `ERE_LID` VARCHAR(1)
, `JAAR_ERE_LID` VARCHAR(4)
, `OMROEPERS` VARCHAR(1)
, `UMPIRE` VARCHAR(10)
, `WEDSTR_SECR` VARCHAR(1)
, `TWEEDE_PENNINGM` VARCHAR(1)
, `LEDENADMIN` VARCHAR(1)
, `STRIKE` VARCHAR(1)
, `CONTRIBUTIE` DECIMAL(6,2)
, `KADERKORTING` DECIMAL(6,2)
, `GEZINSKORTING` DECIMAL(6,2)
,  CONSTRAINT `LDN_PK` PRIMARY KEY (`VOLGNR`)
,  CONSTRAINT `LDN_TLD_FK` FOREIGN KEY (`TLD_VOLGNR`) REFERENCES `BSM_TYPE_LEDEN` (`VOLGNR`) 
);

CREATE TABLE `BSM_LID_CIE` 
( `VOLGNR` BIGINT NOT NULL 
, `LID_VOLGNR` BIGINT NOT NULL 
, `CIE_VOLGNR` BIGINT NOT NULL 
);

CREATE TABLE `BSM_MENU` 
( `MNU_VOLGNR` BIGINT NOT NULL 
, `OMSCHRIJVING` VARCHAR(200) NOT NULL 
, `URL` VARCHAR(500)
, `HINT` VARCHAR(500)
, `PLAATJE` VARCHAR(500)
, `NIVO` TINYINT
, `PARENT` BIGINT
, `WIDTH` BIGINT
, `TARGET` VARCHAR(100)
, `OMSCHRIJVINGLANG` VARCHAR(500)
, `TOON_VOLGNR` BIGINT
, `HELPTEKST` LONGTEXT
,  CONSTRAINT `MNU_PK` PRIMARY KEY (`MNU_VOLGNR`)
,  CONSTRAINT `MNU_MNU_FK` FOREIGN KEY (`PARENT`) REFERENCES `BSM_MENU` (`MNU_VOLGNR`) 
);

ALTER TABLE `BSM_MENU`  COMMENT 'Gebruikt voor beheermenu Oracle';

CREATE TABLE `BSM_SUBSCRIPTIONS` 
( `SSN_KEY` BIGINT NOT NULL  COMMENT 'Technical Id'
, `ANOUNCEMENT` LONGTEXT NOT NULL  COMMENT 'The anouncement will be displayed as a startpoint to the subscribtion-page'
, `GBR_KEY` BIGINT NOT NULL  COMMENT 'Foreign Key to the user-table. The e-mail address of the user can be set'
, `LASTNAME_SUBSCRIBER` VARCHAR(200) COMMENT 'Lastname of the subscriber'
, `FIRSTNAME_SUBSCRIBER` VARCHAR(200) COMMENT 'Firstname of the subscriber'
, `MIDDELNAME_SUBSCRIBER` VARCHAR(200) COMMENT 'Middlename of the subscriber'
, `EMAIL_SUBSCRIBER` VARCHAR(200) COMMENT 'E-mail address of the subscriber'
, `PHONE_SUBSCRIBER` VARCHAR(200) COMMENT 'Phonenumber of the subscriber'
, `TITLE` VARCHAR(100) NOT NULL  COMMENT 'Title of the subscritions as will be displayed above the anouncement'
, `STARTDATE` DATE COMMENT 'The begindate of the subscribtion'
, `ENDDATE` DATE COMMENT 'The enddate of the subscribtion'
, `DATE_CREATED` DATE NOT NULL  COMMENT 'The date of creation'
, `ARCHIVE` VARCHAR(1) DEFAULT 'N' NOT NULL  COMMENT 'Is the record put in archive'
, `LANGUAGE` VARCHAR(2) DEFAULT 'NL' COMMENT 'The language of this subscription'
,  CONSTRAINT `SSN_KEY` PRIMARY KEY (`SSN_KEY`)
,  CONSTRAINT `SSN_GBR_KEY` FOREIGN KEY (`GBR_KEY`) REFERENCES `GEBRUIKERS` (`VOLGNR`) 
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`SSN_KEY` IS 'Technical Id'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`ANOUNCEMENT` IS 'The anouncement will be displayed as a startpoint to the subscribtion-page'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`GBR_KEY` IS 'Foreign Key to the user-table. The e-mail address of the user can be set'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`LASTNAME_SUBSCRIBER` IS 'Lastname of the subscriber'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`FIRSTNAME_SUBSCRIBER` IS 'Firstname of the subscriber'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`MIDDELNAME_SUBSCRIBER` IS 'Middlename of the subscriber'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`EMAIL_SUBSCRIBER` IS 'E-mail address of the subscriber'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`PHONE_SUBSCRIBER` IS 'Phonenumber of the subscriber'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`TITLE` IS 'Title of the subscritions as will be displayed above the anouncement'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`STARTDATE` IS 'The begindate of the subscribtion'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`ENDDATE` IS 'The enddate of the subscribtion'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`DATE_CREATED` IS 'The date of creation'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`ARCHIVE` IS 'Is the record put in archive'; */
/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_SUBSCRIPTIONS`.`LANGUAGE` IS 'The language of this subscription'; */

CREATE TABLE `DEELNEMERS` 
( `VOLGNR` BIGINT
, `ACHTERNAAM` VARCHAR(100) DEFAULT NULL
, `TUSSENVOEGSEL` VARCHAR(50) DEFAULT NULL
, `VOORNAAM` VARCHAR(50) DEFAULT NULL
, `POSITIES` VARCHAR(50) DEFAULT NULL
, `TEM_VOLGNR` BIGINT DEFAULT NULL
, `SDS_VOLGNR` BIGINT DEFAULT NULL
, `FOTO` VARCHAR(1000)
, `RUGNUMMER` BIGINT
, `GEBOORTEDATUM` DATE
, `LIDNUMMER` VARCHAR(10)
, `STRAATNAAM` VARCHAR(200)
, `HUISNUMMER` VARCHAR(10)
, `POSTCODE` VARCHAR(6)
, `PLAATS` VARCHAR(200)
, `TELEFOON` VARCHAR(12)
, `ALTERNATIEFMOB` VARCHAR(12)
, `EMAIL` VARCHAR(500)
, `BEGINDATUMLID` DATE
, `TEST` VARCHAR(20)
, CONSTRAINT `DNSPK` PRIMARY KEY (`VOLGNR`)
, CONSTRAINT `DNS_SDS_FK` FOREIGN KEY (`SDS_VOLGNR`) REFERENCES `SOORT_DEELNEMERS` (`VOLGNR`) 
);

ALTER TABLE `DEELNEMERS`  COMMENT 'Huidige leden tabel (spelers)';

CREATE TABLE `GASTENBOEK` 
( `VOLGNR` BIGINT
, `OPMERKING` VARCHAR(2000) DEFAULT NULL
, `NAAM` VARCHAR(255) DEFAULT NULL
, `EMAIL` VARCHAR(255) DEFAULT NULL
, `HOMEPAGENAAM` VARCHAR(255) DEFAULT NULL
, `HOMEPAGE` VARCHAR(255) DEFAULT NULL
, `TYPE_GASTENBOEK` BIGINT DEFAULT NULL
, `DATUM` DATE DEFAULT NULL
, CONSTRAINT `GTK_PK` PRIMARY KEY (`VOLGNR`)
, CONSTRAINT `GTK_TGK_FK` FOREIGN KEY (`TYPE_GASTENBOEK`) REFERENCES `TYPE_GASTENBOEK` (`VOLGNR`) 
);

ALTER TABLE `GASTENBOEK`  COMMENT 'Gastenboek';

CREATE TABLE `INFO` 
( `VOLGNR` BIGINT NOT NULL 
, `TITEL` VARCHAR(60) DEFAULT NULL
, `TITEL_EN` VARCHAR(60) DEFAULT NULL
, `BERICHT` LONGTEXT
, `BERICHT_EN` LONGTEXT
, `PLAATJE` VARCHAR(100) DEFAULT NULL
, `DATUM_BERICHT` DATE DEFAULT NULL
, `EINDDATUM_BERICHT` DATE DEFAULT NULL
, `GBR_VOLGNR` BIGINT DEFAULT NULL
, `TYPE_INFO` BIGINT DEFAULT NULL
, `PGA_VOLGNR` BIGINT DEFAULT NULL
, `PGA_EN_VOLGNR` BIGINT DEFAULT NULL
, `URL` VARCHAR(255) DEFAULT NULL
, `URL_OMSCHRIJVING` VARCHAR(255) DEFAULT NULL
, `URL_OMSCHRIJVING_EN` VARCHAR(255) DEFAULT NULL
, `URL_EN` VARCHAR(255) DEFAULT NULL
, `DISPLAY_VOLGNR` BIGINT DEFAULT NULL
, `TOON_OP_HOMEPAGE` VARCHAR(1) DEFAULT NULL
, `ARCHIEF` VARCHAR(1)
, `DATUM_GEWIJZIGD` DATE
, `GBR_VOLGNR_GEWIJZIGD` BIGINT
, `AUTO_ARCHIEF` VARCHAR(1)
, `VERMELD_AUTEUR` VARCHAR(1)
, `INLEIDING` LONGTEXT
, `INLEIDING_EN` LONGTEXT
, CONSTRAINT `IFO_PK` PRIMARY KEY (`VOLGNR`)
, CONSTRAINT `IFO_TIO_FK` FOREIGN KEY (`TYPE_INFO`) REFERENCES `TYPE_INFO` (`VOLGNR`) 
);

ALTER TABLE `INFO`  COMMENT 'Informatie Items';

CREATE TABLE `WEDSTRIJDEN` 
( `VOLGNR` BIGINT NOT NULL 
, `DATUM` DATE DEFAULT NULL
, `THUIS_UIT` VARCHAR(1) DEFAULT NULL
, `TEGENSTANDER` VARCHAR(100) DEFAULT NULL
, `TIJDSTIP` VARCHAR(10) DEFAULT NULL
, `PUNTEN_VOOR` VARCHAR(10) DEFAULT NULL
, `PUNTEN_TEGEN` VARCHAR(10) DEFAULT NULL
, `TEAM_VOLGNR` BIGINT DEFAULT NULL
, `SOORT` VARCHAR(3) DEFAULT NULL
, `TEAM_NAAM` VARCHAR(100) DEFAULT NULL
, `OPMERKING` VARCHAR(50) DEFAULT NULL
, `TYPE_WEDSTRIJD` VARCHAR(10) DEFAULT NULL
, `SCHEIDSRECHTERS` VARCHAR(100)
, `WEDSTRIJD_NUMMER` VARCHAR(10)
, `ARCHIEF` VARCHAR(1)
, `VELD_INFO` BIGINT
, `AFGELAST` VARCHAR(1)
, CONSTRAINT `WSD_PK` PRIMARY KEY (`VOLGNR`)
, CONSTRAINT `WSD_SLE_FK` FOREIGN KEY (`VELD_INFO`) REFERENCES `BSM_SPEELLOKATIES` (`VOLGNR`) 
, CONSTRAINT `WSD_TEM_FK` FOREIGN KEY (`TEAM_VOLGNR`) REFERENCES `TEAMS` (`VOLGNR`) 
);

ALTER TABLE `WEDSTRIJDEN`  COMMENT 'Wedstrijden';

CREATE TABLE `BSM_MIJN_DOCUMENTS` 
( `VOLGNR` BIGINT NOT NULL 
, `NAAM` VARCHAR(1000) NOT NULL 
, `DIRECTORY` VARCHAR(1) COMMENT 'J of N'
, `MDS_VOLGNR` BIGINT COMMENT 'mogelijke parent'
, `OMSCHRIJVING` VARCHAR(2000) COMMENT 'omschrijving'
, `TYPE` VARCHAR(500) COMMENT 'type'
, `OPSLAGNAAM` VARCHAR(1000)
, `GBR_VOLGNR` BIGINT
, `DATUM_AANGEMAAKT` DATE
, `PUBLISHED` VARCHAR(1)
, CONSTRAINT `MDS_PK` PRIMARY KEY (`VOLGNR`) 
, CONSTRAINT `MDS_MDS_FK` FOREIGN KEY (`MDS_VOLGNR`) REFERENCES `BSM_MIJN_DOCUMENTS` (`VOLGNR`) 
);

/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_MIJN_DOCUMENTS`.`DIRECTORY` IS 'J of N'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_MIJN_DOCUMENTS`.`MDS_VOLGNR` IS 'mogelijke parent'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_MIJN_DOCUMENTS`.`OMSCHRIJVING` IS 'omschrijving'; */

/* Moved to CREATE TABLE
COMMENT ON COLUMN `BSM_MIJN_DOCUMENTS`.`TYPE` IS 'type'; */
